### ISSUE TITLE
Not Compatible with Gridsome

### ISSUE THREAD

**Issue by Tragio** [igaloly/vue-preloaders#11]
Hello @igaloly! 🙂 

Thank you very much for your work and for this amazing plugin.

I was trying to use it for the first time with Gridsome but I have the following error when building `gridsome build`:
![Screenshot 2020-11-18 at 14 19 47](https://user-images.githubusercontent.com/5109593/99541782-27455880-29a9-11eb-85c6-6edfe1b8fb88.jpg)

However, when I use `gridsome develop` it works perfectly. I think this is due to SSR support but I have not figured out a way to put it working. [https://gridsome.org/docs/assets-scripts/#without-ssr-support](https://gridsome.org/docs/assets-scripts/#without-ssr-support)

I have the following code on `main.js`:

```js
import VuePreloaders from 'vue-preloaders'

export default function(Vue, { router, head, isClient }) {
  Vue.component('Layout', DefaultLayout)
  Vue.use(VuePreloaders)
}
```

And the following code on `layouts/Default.vue`:

```js
mounted() {
    const close = this.$preloaders.open({
      component: Preloader,
      cssStyle: {
        position: 'fixed'
      },
      overlayStyle: {
        background:
          'radial-gradient(circle, rgba(74,74,74,1) 0%, rgba(61,61,61,1) 100%)',
        opacity: 1
      }
    })
    setTimeout(close, 2000)
  }
```

Thank you very much!

**Comment by igaloly** [comment]
Hey @Tragio , Sorry for the delay :(
WIP

**Comment by igaloly** [comment]
Hi @Tragio ,
It seems like the problem solved in **fix-ssr-build** branch.
You need to import the **styles** file from **dist** folder in main.js as well.
In my tests, the builds were successfully completed and the static files were served as expected.
It'll be great if you will check and confirm :)
Waiting for your reply.

**Comment by Tragio** [comment]
> Hi @Tragio ,
> It seems like the problem solved in **fix-ssr-build** branch.
> You need to import the **styles** file from **dist** folder in main.js as well.
> In my tests, the builds were successfully completed and the static files were served as expected.
> It'll be great if you will check and confirm :)
> Waiting for your reply.

All seems fine from my end. I'll let you know if anything comes up. Would be awesome if you could merge into master and perhaps add the above information on the README 😄. Really thank you for your work and support. Happy new year 🎆
