### ISSUE TITLE
Typescript support? please :'c

### ISSUE THREAD

**Issue by davidreyg** [igaloly/vue-preloaders#13]
I think your library is awesome! Can you guys add support for Typescript? Thanks!

**Comment by igaloly** [comment]
Hi @davidreyg, Sorry for the delay :(
It's definitely a great idea, but unfortunately, I don't see when I can devote time to that.
If you would like, I can guide you through the source code and give you an understanding of the project so that you'll be able to implement TS types but your-self :)
