### ISSUE TITLE
Order of operations to successfully utilize this plugin with Nuxt 2.

### ISSUE THREAD

**Issue by mattyricks** [igaloly/vue-preloaders#25]
Hello, I wanted to preface with how seemingly simple this implementation looks when reviewing the documentation but I just do not know what I am doing wrong here. 

The flow of my application is more or less as such:
- Application running locally routes user to pages/index.vue
- This index.vue is using a _Custom Layout_ called 'preloader'
- This _Custom Layout_ is where I am creating the custom preloader component and using this.$preloaders.open()
- This will initiate a setTimeout function and then re-route the user to the endpoint '/intro'

**It sounds easy but I just can't figure this out.**

###  1.  using NPM to install the dependency
 `npm install vue-preloaders --save`
  <br />

###  2. Created the plugins/ directory and added a new file:  _preloaders.js_
> nuxt.config.js
```
export default {
  plugins: ['~/plugins/preloaders.js']
}
```

###  3. Transpile the _dependency_ inside of the **build** object's **transpile** array
> nuxt.config.js
```
  build: {
    transpile: ['vue-preloaders'],
  },
```

###  4. Add the minified css into the css dependencies array
> nuxt.config.js
```
  css: [
    'vue-preloaders/dist/vue-preloaders.css',
  ],
```

###  5. The preloaders.js plugin that I added to the nuxt.config.js
```
// NOTE: Here I am follow the Nuxt Plugins documentation:
import Vue from 'vue'
import VuePreloaders from 'vue-preloaders'

// NOTE: Here I am importing the custom preloader 
import Squares from '../layouts/preloader'

Vue.use(VuePreloaders, {
  loaders: {
    squareLoader: {
      container: '#app',
      component: Squares,
      overlayStyle: { backgroundColor: '#121212' },
    },
  },
})
```

I am trying to put this problem into words the best that I can. I think I am over-complicating this issue. Any help would be very much appreciated.

Kind regards,

Matthew

**Comment by igaloly** [comment]
Hey. Sorry for the inconvenience :\
I do not maintain this repo anymore.
