### ISSUE TITLE
Your nuxt config correct?

### ISSUE THREAD

**Issue by Reglament989** [igaloly/vue-preloaders#6]
![image](https://user-images.githubusercontent.com/52096394/83188146-c7b77000-a11e-11ea-90d3-31f7132d66f8.png)
nuxt 2.0 with express

**Comment by igaloly** [comment]
> ![image](https://user-images.githubusercontent.com/52096394/83188146-c7b77000-a11e-11ea-90d3-31f7132d66f8.png)
> nuxt 2.0 with express

Thank you very much for the feedback.
Fixed in v1.0.13 :)
